const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best');
const overlay=document.querySelector('#overlay'),startBtn=document.querySelector('#start'),titleEl=document.querySelector('#game-title'),subEl=document.querySelector('#game-subtitle'),kickEl=document.querySelector('#game-kicker'),howEl=document.querySelector('#how');
const game=new URLSearchParams(location.search).get('game')||'pacman';let running=false,score=0,raf,keys={};let activeBlockWorld=null;
let gdLevel='stereo',practiceMode=false;const gdConfigs={stereo:{label:'STEREO MADNESS',speed:255,next:1.35,finish:460,platforms:false},backtrack:{label:'BACK ON TRACK',speed:300,next:1.12,finish:145,platforms:true},polargeist:{label:'POLARGEIST',speed:340,next:.92,finish:170,platforms:true}};const gdOptions=document.querySelector('#gd-options');if(game==='gd'&&gdOptions){gdOptions.hidden=false;document.querySelector('#gd-level').addEventListener('change',e=>{gdLevel=e.target.value;});document.querySelector('#gd-practice').addEventListener('change',e=>{practiceMode=e.target.checked;});}const dinoOptions=document.querySelector('#dino-options');if(game==='dino'&&dinoOptions){dinoOptions.hidden=false;}
const pacmanOptions=document.querySelector('#pacman-options');let pacmanDifficulty=1;const pacmanScoreMultiplier=level=>Math.min(4,1+Math.floor((level-1)/25));if(game==='pacman'&&pacmanOptions){pacmanOptions.hidden=false;const slider=document.querySelector('#pacman-difficulty');const label=document.querySelector('#pacman-difficulty-label');const update=()=>{pacmanDifficulty=Math.max(1,Math.min(100,Number(slider.value)||1));label.textContent=`${pacmanDifficulty===1?'EXTRA EASY':`LEVEL ${pacmanDifficulty}`} · ${pacmanScoreMultiplier(pacmanDifficulty)}× SCORE`;};slider.addEventListener('input',update);update();document.body.classList.add('pacman-page');}
const meta={pacman:['Maze Muncher','ARCADE CLASSIC','Clear the maze. Dodge the ghosts. Chase a new high score.','Use arrow keys or WASD. Collect dots, grab cherries, and clear every corridor before you lose your lives.'],blocks:['Block Quest','CREATIVE MODE','Dig deep, gather gems, and build your way to the sky.','Move with arrows or WASD. Click blocks to mine them, then press Space to place a block nearby.'],football:['Pocket Football','SPORTS CHALLENGE','Aim your shot. Beat the keeper. Find the top corner.','Move the target with arrows or WASD, then press Space or tap the game to shoot.'],dino:['Chrome Dino','ARCADE RUNNER','Jump the cacti and survive as the desert gets faster.','Press Space, ArrowUp, or W to jump. The longer you survive, the faster it gets.'],gd:['Cube Rush','GEOMETRY RUNNER','Choose a premade level, chase 100%, or practice from checkpoints.','Pick Stereo Madness, Back on Track, Polargeist, or Wave Run. Hold Space, ArrowUp, or W to control your jump or wave.']};
[titleEl.textContent,kickEl.textContent,subEl.textContent,howEl.textContent]=meta[game]||meta.pacman;document.title=`${titleEl.textContent} — Recess Arcade`;
function blockWorldStorage(){try{return JSON.parse(localStorage.getItem('recess-block-worlds')||'[]')}catch(error){return []}}
function saveBlockWorlds(worlds){try{localStorage.setItem('recess-block-worlds',JSON.stringify(worlds))}catch(error){/* offline storage may be restricted */}}
function renderBlockWorlds(){const list=document.querySelector('#block-world-list'),enter=document.querySelector('#start-block-world'),deleteButton=document.querySelector('#delete-block-world');if(!list)return;const worlds=blockWorldStorage();list.innerHTML='';if(!worlds.length){list.innerHTML='<div class="block-world-empty">No saved worlds yet. Create one below.</div>'}worlds.forEach(world=>{const card=document.createElement('button');card.type='button';card.className='block-world-card'+(activeBlockWorld&&activeBlockWorld.id===world.id?' selected':'');card.innerHTML=`<strong>${world.name}</strong><span>${world.mod.toUpperCase()} · ${world.score||0} XP</span>`;card.addEventListener('click',()=>selectBlockWorld(world.id));list.appendChild(card)});if(enter)enter.disabled=!activeBlockWorld;if(deleteButton)deleteButton.disabled=!activeBlockWorld}
function selectBlockWorld(id){const world=blockWorldStorage().find(item=>item.id===id);if(!world)return;activeBlockWorld=world;const name=document.querySelector('#block-world-name'),mod=document.querySelector('#block-mod'),survival=document.querySelector('#block-survival'),night=document.querySelector('#block-night'),friendly=document.querySelector('#block-friendly'),status=document.querySelector('#block-world-status');if(name)name.value=world.name;if(mod)mod.value=world.mod;if(survival)survival.checked=world.settings.survival;if(night)night.checked=world.settings.night;if(friendly)friendly.checked=world.settings.friendly;if(status)status.textContent='Selected '+world.name+'. Enter when ready.';renderBlockWorlds()}
function setupBlockWorldHome(){if(game!=='blocks')return;const panel=document.querySelector('#blocks-options'),overlayNode=document.querySelector('#overlay');if(!panel)return;panel.hidden=false;if(overlayNode)overlayNode.hidden=true;const create=document.querySelector('#create-block-world'),deleteButton=document.querySelector('#delete-block-world'),enter=document.querySelector('#start-block-world'),status=document.querySelector('#block-world-status');renderBlockWorlds();create.addEventListener('click',()=>{const name=(document.querySelector('#block-world-name').value||'New Frontier').trim().slice(0,24)||'New Frontier';const world={id:String(Date.now()),name,mod:document.querySelector('#block-mod').value,settings:{survival:document.querySelector('#block-survival').checked,night:document.querySelector('#block-night').checked,friendly:document.querySelector('#block-friendly').checked},score:0,blocks:0};const worlds=blockWorldStorage();worlds.push(world);saveBlockWorlds(worlds);activeBlockWorld=world;if(status)status.textContent='World created and saved offline.';renderBlockWorlds()});deleteButton.addEventListener('click',()=>{if(!activeBlockWorld)return;saveBlockWorlds(blockWorldStorage().filter(world=>world.id!==activeBlockWorld.id));activeBlockWorld=null;if(status)status.textContent='World deleted.';renderBlockWorlds()});enter.addEventListener('click',()=>{if(!activeBlockWorld)return;panel.hidden=true;setScore(activeBlockWorld.score||0);running=true;blocksAdvanced(activeBlockWorld)});}
if(game==='blocks')setupBlockWorldHome();
const touchPad=document.querySelector('#touch');
if(touchPad){
  const touchButtons=[...touchPad.querySelectorAll('button')];
  const jumpOnly=['dino','gd'].includes(game);
  touchPad.classList.toggle('jump-only',jumpOnly);
  if(jumpOnly){const jumpButton=touchPad.querySelector('[data-key="Space"]');if(jumpButton){jumpButton.textContent='JUMP';jumpButton.setAttribute('aria-label','Hold to jump');}}
  if(game==='blocks'){const placeButton=touchPad.querySelector('[data-key="Space"]');if(placeButton){placeButton.textContent='PLACE';placeButton.setAttribute('aria-label','Place block');}}
  touchButtons.forEach(button=>{button.addEventListener('pointercancel',()=>{keys[button.dataset.key]=false;});});
}
let best=Number(localStorage.getItem(`recess-${game}`)||0);bestEl.textContent=String(best).padStart(3,'0');
function setScore(n){score=n;scoreEl.textContent=String(n).padStart(3,'0');if(n>best){best=n;bestEl.textContent=String(best).padStart(3,'0');localStorage.setItem(`recess-${game}`,best)}}
function end(msg){running=false;cancelAnimationFrame(raf);document.querySelector('#overlay-title').textContent='ROUND OVER';document.querySelector('#overlay-copy').textContent=msg;startBtn.textContent='PLAY AGAIN';overlay.hidden=false}
addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);
addEventListener('keydown',e=>{if(game==='dino'&&e.code==='KeyH'){const control=document.querySelector('#dino-hitboxes');if(control){control.checked=!control.checked;control.dispatchEvent(new Event('change'));}}});
document.querySelectorAll('#touch button').forEach(b=>{const code=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[code]=true});b.addEventListener('pointerup',()=>keys[code]=false)});
function pacman(){const S=50,cols=16,rows=10,walls=new Set(),dots=new Set();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(x===0||y===0||x===cols-1||y===rows-1||(x%3===0&&y%3!==1))walls.add(`${x},${y}`);else dots.add(`${x},${y}`)}let p={x:1,y:1},dir={x:0,y:0},ghosts=[{x:14,y:8,c:'#ff5a4e'},{x:14,y:1,c:'#ff82b2'}],tick=0;dots.delete('1,1');function draw(){ctx.fillStyle='#10182d';ctx.fillRect(0,0,800,500);walls.forEach(k=>{let[x,y]=k.split(',').map(Number);ctx.fillStyle='#2563eb';ctx.fillRect(x*S+4,y*S+4,S-8,S-8)});dots.forEach(k=>{let[x,y]=k.split(',').map(Number);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x*S+25,y*S+25,4,0,7);ctx.fill()});ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.arc(p.x*S+25,p.y*S+25,18,.2,Math.PI*1.8);ctx.lineTo(p.x*S+25,p.y*S+25);ctx.fill();ghosts.forEach(g=>{ctx.fillStyle=g.c;ctx.beginPath();ctx.arc(g.x*S+25,g.y*S+25,17,Math.PI,0);ctx.lineTo(g.x*S+42,g.y*S+42);ctx.lineTo(g.x*S+8,g.y*S+42);ctx.fill()})}
function loop(){if(!running)return;tick++;if(tick%7===0){let nd=keys.ArrowLeft||keys.KeyA?{x:-1,y:0}:keys.ArrowRight||keys.KeyD?{x:1,y:0}:keys.ArrowUp||keys.KeyW?{x:0,y:-1}:keys.ArrowDown||keys.KeyS?{x:0,y:1}:dir;if(!walls.has(`${p.x+nd.x},${p.y+nd.y}`))dir=nd;if(!walls.has(`${p.x+dir.x},${p.y+dir.y}`)){p.x+=dir.x;p.y+=dir.y}let k=`${p.x},${p.y}`;if(dots.delete(k))setScore(score+10);ghosts.forEach(g=>{let opts=[[1,0],[-1,0],[0,1],[0,-1]].filter(d=>!walls.has(`${g.x+d[0]},${g.y+d[1]}`));let d=opts[Math.floor(Math.random()*opts.length)];g.x+=d[0];g.y+=d[1];if(g.x===p.x&&g.y===p.y)end('A ghost caught you! Try another route.');});if(!dots.size)end('Maze cleared! That was a perfect run.')}draw();raf=requestAnimationFrame(loop)}loop()}
function blocksAdvanced(world){const size=50,cols=16,rows=10,mod=world.mod||'classic',oneBlock=mod==='oneblock',creatureMode=mod==='creaturemon';let grid=Array.from({length:rows},(_,y)=>Array.from({length:cols},(_,x)=>y>5?((x*7+y*3)%13===0?2:1):0)),p={x:7,y:5},inv=0,tick=0,spaceOld=false,worldTime=0,creatures=creatureMode?[{x:3,y:5,name:'Spriglet',color:'#7af29c',caught:false},{x:11,y:5,name:'Emberpaw',color:'#ff8d68',caught:false},{x:13,y:4,name:'Aquaffin',color:'#68c9ff',caught:false}]:[],oneBlockLevel=0;
  function saveProgress(){const worlds=blockWorldStorage();const current=worlds.find(item=>item.id===world.id);if(current){current.score=Math.floor(score);current.blocks=inv;saveBlockWorlds(worlds)}}
  function draw(){const night=world.settings.night&&Math.sin(worldTime*.004)<-.35;ctx.fillStyle=night?'#182342':'#7ed6f7';ctx.fillRect(0,0,800,500);grid.forEach((r,y)=>r.forEach((v,x)=>{if(v){ctx.fillStyle=v===2?'#59e2c2':y===6?'#5dbd56':'#9c653c';ctx.fillRect(x*size,y*size,size,size);ctx.strokeStyle='rgba(20,33,61,.25)';ctx.strokeRect(x*size,y*size,size,size)}}));if(oneBlock){ctx.fillStyle='#ffd23f';ctx.fillRect(7*size+4,6*size+4,size-8,size-8);ctx.fillStyle='#14213d';ctx.font='bold 10px Arial';ctx.fillText('ONE BLOCK '+(oneBlockLevel+1),7*size+5,6*size+27)}if(creatureMode){creatures.forEach(c=>{if(c.caught)return;const bob=Math.sin(worldTime*.006+c.x)*4;ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(c.x*size+25,c.y*size+25+bob,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#14213d';ctx.fillRect(c.x*size+18,c.y*size+20+bob,4,4);ctx.fillRect(c.x*size+29,c.y*size+20+bob,4,4);ctx.fillStyle='#fff';ctx.font='bold 10px Arial';ctx.fillText(c.name,c.x*size+3,c.y*size+7+bob)})}ctx.fillStyle='#ffd23f';ctx.fillRect(p.x*size+10,p.y*size+5,30,45);ctx.fillStyle='#14213d';ctx.fillRect(p.x*size+15,p.y*size+14,5,5);ctx.fillRect(p.x*size+30,p.y*size+14,5,5);ctx.fillStyle='#fff';ctx.font='bold 16px Arial';ctx.fillText(`BLOCKS: ${inv}  ${world.name}`,15,28);ctx.font='bold 12px Arial';ctx.fillText(`MOD: ${oneBlock?'ONE BLOCK':creatureMode?'CREATUREMON':'CLASSIC'}${creatureMode?' · CAUGHT '+creatures.filter(c=>c.caught).length+'/'+creatures.length:''}`,15,48)}
  function mine(e){if(!running)return;const rect=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-rect.left)*800/rect.width/size),y=Math.floor((e.clientY-rect.top)*500/rect.height/size);if(creatureMode){const caught=creatures.find(c=>!c.caught&&c.x===x&&c.y===y);if(caught){caught.caught=true;setScore(score+80);saveProgress();return}}if(oneBlock&&x===7&&y===6&&Math.abs(x-p.x)<=3){oneBlockLevel+=1;inv+=1;setScore(score+10+oneBlockLevel*3);saveProgress();return}if(grid[y]?.[x]&&Math.abs(x-p.x)<=2&&Math.abs(y-p.y)<=2){setScore(score+(grid[y][x]===2?50:5));grid[y][x]=0;inv++;saveProgress()}}
  canvas.onclick=mine;function loop(){if(!running)return;tick++;worldTime+=1;if(tick%8===0){const dx=(keys.ArrowLeft||keys.KeyA?-1:0)+(keys.ArrowRight||keys.KeyD?1:0);if(dx&&p.x+dx>=0&&p.x+dx<cols)p.x+=dx;while(p.y<rows-1&&!grid[p.y+1][p.x]&&!(oneBlock&&p.x===7&&p.y+1===6))p.y++;if((keys.ArrowUp||keys.KeyW)&&grid[p.y+1]?.[p.x]&&p.y>0)p.y--;const sp=keys.Space;if(sp&&!spaceOld&&inv>0){const y=p.y+1;if(grid[y]&&!grid[y][p.x]){grid[y][p.x]=1;inv--;saveProgress()}}spaceOld=sp}draw();raf=requestAnimationFrame(loop)}loop()}

function blocks(){return blocksAdvanced({id:'quick',name:'Quick World',mod:'classic',settings:{survival:true,night:true,friendly:true},score:0,blocks:0})}
function football(){let target={x:400,y:230},keeper={x:400,dir:1},shots=5,spaceOld=false,cool=0;function draw(){ctx.fillStyle='#55b85b';ctx.fillRect(0,0,800,500);ctx.strokeStyle='#fff';ctx.lineWidth=6;ctx.strokeRect(130,60,540,250);for(let x=130;x<670;x+=45){ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x,310);ctx.stroke()}ctx.beginPath();ctx.arc(target.x,target.y,20,0,7);ctx.strokeStyle='#ffd23f';ctx.stroke();ctx.fillStyle='#ff5a4e';ctx.fillRect(keeper.x-45,245,90,22);ctx.font='70px Arial';ctx.fillText('⚽',365,445);ctx.fillStyle='#fff';ctx.font='bold 18px Arial';ctx.fillText(`SHOTS LEFT: ${shots}`,20,30)}function shoot(){if(cool||shots<=0)return;shots--;cool=25;const save=Math.abs(target.x-keeper.x)<80&&target.y>190;if(!save)setScore(score+100);if(shots===0)setTimeout(()=>end(`Final score: ${score}. Aim away from the moving keeper!`),500)}canvas.onclick=()=>shoot();function loop(){if(!running)return;keeper.x+=keeper.dir*5;if(keeper.x>600||keeper.x<200)keeper.dir*=-1;target.x=Math.max(150,Math.min(650,target.x+(keys.ArrowLeft||keys.KeyA?-4:0)+(keys.ArrowRight||keys.KeyD?4:0)));target.y=Math.max(85,Math.min(280,target.y+(keys.ArrowUp||keys.KeyW?-4:0)+(keys.ArrowDown||keys.KeyS?4:0)));let sp=keys.Space;if(sp&&!spaceOld)shoot();spaceOld=sp;if(cool)cool--;draw();raf=requestAnimationFrame(loop)}loop()}
function pacmanSmooth(){const S=50,cols=16,rows=10,stepMs=175,walls=new Set(),dots=new Set();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(y===0||y===rows-1||(x%3===0&&y%3!==1))walls.add(`${x},${y}`);else dots.add(`${x},${y}`)}const p={x:1,y:1,vx:1,vy:1};let dir={x:0,y:0};const ghosts=[{x:14,y:8,vx:14,vy:8,c:'#ff5a4e'},{x:14,y:1,vx:14,vy:1,c:'#ff82b2'},{x:7,y:8,vx:7,vy:8,c:'#54d6ff'}];dots.delete('1,1');let last=performance.now(),step=0,fpsFrames=0,fpsTime=last,mazeAwarded=false,dotPointBuffer=0;function wrapX(x){return (x+cols)%cols}function cellAt(x,y){if(y<0||y>=rows)return null;return{x:wrapX(x),y:y}}function canMove(x,y){const cell=cellAt(x,y);return !!cell&&!walls.has(`${cell.x},${cell.y}`)}function moveEntity(entity,dx,dy){const cell=cellAt(entity.x+dx,entity.y+dy);if(!cell||walls.has(`${cell.x},${cell.y}`))return false;entity.x=cell.x;entity.y=cell.y;return true}function draw(now){ctx.fillStyle='#10182d';ctx.fillRect(0,0,800,500);walls.forEach(k=>{const[x,y]=k.split(',').map(Number);ctx.fillStyle='#2563eb';ctx.fillRect(x*S+4,y*S+4,S-8,S-8);ctx.strokeStyle='#55a6ff';ctx.lineWidth=2;ctx.strokeRect(x*S+8,y*S+8,S-16,S-16)});ctx.fillStyle='rgba(84,214,255,.16)';ctx.fillRect(0,2,S,rows*S-4);ctx.fillRect((cols-1)*S+2,2,S-4,rows*S-4);dots.forEach(k=>{const[x,y]=k.split(',').map(Number);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x*S+25,y*S+25,4,0,7);ctx.fill()});const mouth=.18+Math.abs(Math.sin(now*.018))*.22,angle=Math.atan2(dir.y,dir.x)||0;ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.moveTo(p.vx*S+25,p.vy*S+25);ctx.arc(p.vx*S+25,p.vy*S+25,18,angle+mouth,angle+Math.PI*2-mouth);ctx.fill();ghosts.forEach(g=>{const x=g.vx*S+25,y=g.vy*S+25;ctx.fillStyle=g.c;ctx.beginPath();ctx.arc(x,y,17,Math.PI,0);ctx.lineTo(x+17,y+17);ctx.lineTo(x+8,y+11);ctx.lineTo(x,y+17);ctx.lineTo(x-8,y+11);ctx.lineTo(x-17,y+17);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(x-9,y-5,6,8);ctx.fillRect(x+4,y-5,6,8)})}
function logicalStep(){const next=keys.ArrowLeft||keys.KeyA?{x:-1,y:0}:keys.ArrowRight||keys.KeyD?{x:1,y:0}:keys.ArrowUp||keys.KeyW?{x:0,y:-1}:keys.ArrowDown||keys.KeyS?{x:0,y:1}:dir;if(canMove(p.x+next.x,p.y+next.y))dir=next;moveEntity(p,dir.x,dir.y);const dot=`${p.x},${p.y}`;if(dots.delete(dot)){setScore(score+10);dotPointBuffer++;if(dotPointBuffer>=5){window.RecessPoints?.award?.(dotPointBuffer,'Maze dots');dotPointBuffer=0}}ghosts.forEach(g=>{const moves=[[1,0],[-1,0],[0,1],[0,-1]].filter(d=>canMove(g.x+d[0],g.y+d[1]));if(!moves.length)return;moves.sort((a,b)=>(Math.abs(g.x+a[0]-p.x)+Math.abs(g.y+a[1]-p.y))-(Math.abs(g.x+b[0]-p.x)+Math.abs(g.y+b[1]-p.y)));const d=Math.random()<.68?moves[0]:moves[Math.floor(Math.random()*moves.length)];moveEntity(g,d[0],d[1]);if(g.x===p.x&&g.y===p.y)end('A ghost caught you! Try another route.');});if(!dots.size){if(!mazeAwarded){mazeAwarded=true;window.RecessPoints?.award?.(75+dotPointBuffer,'Maze cleared');dotPointBuffer=0}end('Maze cleared! That was a perfect run.')}}
function loop(now){if(!running)return;const dt=Math.min(40,now-last);last=now;step+=dt;while(step>=stepMs){logicalStep();step-=stepMs}const blend=1-Math.exp(-dt*.015);p.vx+=(p.x-p.vx)*blend;p.vy+=(p.y-p.vy)*blend;ghosts.forEach(g=>{g.vx+=(g.x-g.vx)*blend;g.vy+=(g.y-g.vy)*blend});fpsFrames++;if(now-fpsTime>=500){const fps=Math.round(fpsFrames*1000/(now-fpsTime));const el=document.querySelector('#fps');if(el)el.textContent=fps;fpsFrames=0;fpsTime=now}draw(now);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function dino(){let p={x:105,y:390,vy:0,w:34,h:42,onGround:true},obs=[],speed=270,spawn=0,last=performance.now(),oldJump=false;function jump(){if(p.onGround){p.vy=-610;p.onGround=false}}function draw(){ctx.fillStyle='#f7f7f7';ctx.fillRect(0,0,800,500);ctx.fillStyle='#d9d9d9';ctx.fillRect(170,90,58,4);ctx.fillRect(185,83,28,7);ctx.fillRect(520,130,70,4);ctx.fillRect(540,123,32,7);ctx.fillStyle='#535353';ctx.fillRect(0,432,800,3);ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#f7f7f7';ctx.fillRect(p.x+24,p.y+8,7,7);ctx.fillStyle='#535353';obs.forEach(o=>{ctx.fillRect(o.x,432-o.h,o.w,o.h);if(o.h>32)ctx.fillRect(o.x-8,410-o.h,o.w+15,7)});ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP',20,28);ctx.fillText(`SPEED ${Math.round(speed)}`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!oldJump)jump();oldJump=j;p.vy+=1450*dt;p.y+=p.vy*dt;if(p.y>=390){p.y=390;p.vy=0;p.onGround=true}spawn-=dt;if(spawn<=0){obs.push({x:820,w:18+Math.random()*18,h:24+Math.random()*34});spawn=Math.max(.55,1.25-speed/700)}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-60);for(const o of obs)if(p.x+p.w-5>o.x&&p.x+5<o.x+o.w&&p.y+p.h>432-o.h+3){window.RecessPoints?.award?.(Math.floor(score/10),'Dino survival');end(`You survived ${score} meters.`);return}speed+=dt*5;setScore(score+Math.max(1,Math.floor(dt*10)));draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gd(){let p={x:130,y:368,vy:0,w:34,h:34,onGround:true,rot:0},blocks=[],speed=285,spawn=0,last=performance.now(),oldJump=false;function jump(){if(p.onGround){p.vy=-650;p.onGround=false}}function draw(){const grad=ctx.createLinearGradient(0,0,800,500);grad.addColorStop(0,'#20145c');grad.addColorStop(1,'#081e46');ctx.fillStyle=grad;ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.22)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}ctx.fillStyle='#14e6d4';ctx.fillRect(0,402,800,5);ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-17,-17,34,34);ctx.fillStyle='#20145c';ctx.fillRect(-8,-8,6,6);ctx.fillRect(5,-8,6,6);ctx.restore();blocks.forEach(o=>{ctx.fillStyle='#ff4f9a';ctx.beginPath();ctx.moveTo(o.x,402);ctx.lineTo(o.x+o.w/2,402-o.h);ctx.lineTo(o.x+o.w,402);ctx.closePath();ctx.fill()});ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP ON THE BEAT',20,28);ctx.fillText(`RUN ${Math.floor(score)}m`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!oldJump)jump();oldJump=j;p.vy+=1700*dt;p.y+=p.vy*dt;p.rot+=dt*7;if(p.y>=368){p.y=368;p.vy=0;p.onGround=true;p.rot=Math.round(p.rot/(Math.PI/2))*Math.PI/2}spawn-=dt;if(spawn<=0){blocks.push({x:840,w:28+Math.random()*15,h:35+Math.random()*45});spawn=Math.max(.52,1.05-speed/800)}blocks.forEach(o=>o.x-=speed*dt);blocks=blocks.filter(o=>o.x>-60);for(const o of blocks)if(p.x+p.w-5>o.x&&p.x+5<o.x+o.w&&p.y+p.h>402-o.h+4){window.RecessPoints?.award?.(Math.floor(score/8),'Cube Rush');end(`Run ended at ${Math.floor(score)} meters.`);return}speed+=dt*4;setScore(score+dt*10);draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gdTurbo(){let p={x:130,y:368,vy:0,w:34,h:34,onGround:true,rot:0},obs=[],speed=370,next=0,last=performance.now(),old=false;const jump=()=>{if(p.onGround){p.vy=-650;p.onGround=false}};function draw(){const g=ctx.createLinearGradient(0,0,800,500);g.addColorStop(0,'#20145c');g.addColorStop(1,'#081e46');ctx.fillStyle=g;ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.2)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}ctx.fillStyle='#14e6d4';ctx.fillRect(0,402,800,5);ctx.save();ctx.translate(p.x+17,p.y+17);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-17,-17,34,34);ctx.fillStyle='#20145c';ctx.fillRect(-8,-8,6,6);ctx.fillRect(5,-8,6,6);ctx.restore();obs.forEach(o=>{ctx.fillStyle=o.type==='block'?'#ff7a45':'#ff4f9a';if(o.type==='block')ctx.fillRect(o.x,402-o.h,o.w,o.h);else{ctx.beginPath();ctx.moveTo(o.x,402);ctx.lineTo(o.x+o.w/2,402-o.h);ctx.lineTo(o.x+o.w,402);ctx.closePath();ctx.fill()}});ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP',20,28);ctx.fillText(`RUN ${Math.floor(score)}m`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;p.vy+=1700*dt;p.y+=p.vy*dt;p.rot+=dt*8;if(p.y>=368){p.y=368;p.vy=0;p.onGround=true;p.rot=Math.round(p.rot/(Math.PI/2))*Math.PI/2}next-=dt;if(next<=0){const type=Math.random()<.72?'spike':'block',count=Math.random()<.3?2:1;for(let i=0;i<count;i++)obs.push({x:840+i*56,w:type==='block'?24:18+Math.random()*12,h:type==='block'?24+Math.random()*22:25+Math.random()*30,type});next=Math.max(.78,1.45-speed/1000)}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);for(const o of obs)if(p.x+p.w-5>o.x&&p.x+5<o.x+o.w&&p.y+p.h>402-o.h+4){window.RecessPoints?.award?.(Math.floor(score/8),'Cube Rush');end(`Run ended at ${Math.floor(score)} meters.`);return}speed+=dt*5;setScore(score+dt*10);draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function dinoPlus(){let p={x:105,y:390,vy:0,w:34,h:42,onGround:true},obs=[],speed=300,next=0,last=performance.now(),oldJump=false,night=0;function jump(){if(p.onGround){p.vy=-620;p.onGround=false}}function draw(){const dark=Math.floor(night)%2===1;ctx.fillStyle=dark?'#202b4d':'#f7f7f7';ctx.fillRect(0,0,800,500);ctx.fillStyle=dark?'#f5e98a':'#d9d9d9';ctx.beginPath();ctx.arc(dark?680:110,75,24,0,Math.PI*2);ctx.fill();ctx.fillStyle=dark?'#9aa8d0':'#d9d9d9';ctx.fillRect(180,92,58,4);ctx.fillRect(195,85,28,7);ctx.fillStyle=dark?'#b8c6e8':'#535353';ctx.fillRect(0,432,800,3);const duck=keys.ArrowDown||keys.KeyS;ctx.fillRect(p.x,p.y+(duck?12:0),p.w+(duck?13:0),duck?30:p.h-(duck?12:0));ctx.fillStyle=dark?'#202b4d':'#f7f7f7';ctx.fillRect(p.x+24,p.y+8+(duck?12:0),7,7);ctx.fillStyle=dark?'#ff9a62':'#535353';obs.forEach(o=>{if(o.type==='bird'){ctx.fillRect(o.x,432-o.h,o.w,8);ctx.fillRect(o.x+8,432-o.h-8,8,8);ctx.fillRect(o.x+o.w-5,432-o.h-8,8,8)}else{ctx.fillRect(o.x,432-o.h,o.w,o.h);if(o.h>32)ctx.fillRect(o.x-8,410-o.h,o.w+15,7)}});ctx.fillStyle=dark?'#fff':'#535353';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP · ↓ DUCK',20,28);ctx.fillText(`SPEED ${Math.round(speed)}`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!oldJump)jump();oldJump=j;p.vy+=1450*dt;p.y+=p.vy*dt;if(p.y>=390){p.y=390;p.vy=0;p.onGround=true}next-=dt;if(next<=0){const type=Math.random()<.18?'bird':'cactus';obs.push({x:820,w:type==='bird'?30:18+Math.random()*18,h:type==='bird'?75:24+Math.random()*38,type});next=Math.max(.62,1.25-speed/850)}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);const duck=keys.ArrowDown||keys.KeyS;for(const o of obs){const hit=p.x+p.w-5>o.x&&p.x+5<o.x+o.w;if(hit&&(o.type==='bird'?!duck&&p.y+20>432-o.h:p.y+p.h>432-o.h+3)){window.RecessPoints?.award?.(Math.floor(score/10),'Dino survival');end(`You survived ${score} meters.`);return}}speed+=dt*6;night+=dt*.16;setScore(score+Math.max(1,Math.floor(dt*10)));draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gdPlatform(){let p={x:130,y:360,vy:0,w:32,h:32,onGround:true,rot:0},plats=[{x:0,y:402,w:800,h:5},{x:340,y:320,w:170,h:12},{x:680,y:255,w:150,h:12}],obs=[],speed=350,next=1,last=performance.now(),old=false;const jump=()=>{if(p.onGround){p.vy=-670;p.onGround=false}};function draw(){ctx.fillStyle='#17104a';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.2)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}ctx.fillStyle='#14e6d4';plats.forEach(o=>ctx.fillRect(o.x,o.y,o.w,o.h));ctx.save();ctx.translate(p.x+16,p.y+16);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-16,-16,32,32);ctx.restore();ctx.fillStyle='#ff4f9a';obs.forEach(o=>{ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w/2,o.y-o.h);ctx.lineTo(o.x+o.w,o.y);ctx.closePath();ctx.fill()});ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP · LAND ON PLATFORMS',20,28);ctx.fillText(`RUN ${Math.floor(score)}m`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;p.vy+=1750*dt;const prevBottom=p.y+p.h;p.y+=p.vy*dt;p.onGround=false;plats.forEach(o=>{o.x-=speed*dt;if(o.x+o.w<0)o.x=820+Math.random()*180;const crossed=prevBottom<=o.y&&p.y+p.h>=o.y;if(crossed&&p.x+p.w>o.x&&p.x<o.x+o.w&&p.vy>=0){p.y=o.y-p.h;p.vy=0;p.onGround=true}});p.rot+=dt*8;if(p.y>500){end(`Run ended at ${Math.floor(score)} meters.`);return}next-=dt;if(next<=0){const platform=plats[Math.floor(Math.random()*Math.min(3,plats.length))];obs.push({x:platform.x+platform.w*.55,y:platform.y,w:22+Math.random()*12,h:28+Math.random()*25});next=.9+Math.random()*.65}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);for(const o of obs)if(p.x+p.w-4>o.x&&p.x+4<o.x+o.w&&p.y+p.h>o.y-o.h+4&&p.y<o.y){window.RecessPoints?.award?.(Math.floor(score/8),'Cube Rush');end(`Run ended at ${Math.floor(score)} meters.`);return}speed+=dt*4;setScore(score+dt*10);draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gdPlatformFixed(){let p={x:130,y:368,vy:0,w:32,h:32,onGround:true},plats=[{x:0,y:402,w:900,h:5,ground:true},{x:360,y:320,w:170,h:12},{x:700,y:255,w:150,h:12}],obs=[],speed=350,next=1,last=performance.now(),old=false;const jump=()=>{if(p.onGround){p.vy=-670;p.onGround=false}};function draw(){ctx.fillStyle='#17104a';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.2)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}ctx.fillStyle='#14e6d4';plats.forEach(o=>ctx.fillRect(o.x,o.y,o.w,o.h));ctx.save();ctx.translate(p.x+16,p.y+16);ctx.rotate(p.rot||0);ctx.fillStyle='#ffdc4a';ctx.fillRect(-16,-16,32,32);ctx.restore();ctx.fillStyle='#ff4f9a';obs.forEach(o=>{ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w/2,o.y-o.h);ctx.lineTo(o.x+o.w,o.y);ctx.closePath();ctx.fill()});ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP · KEEP THE FLOOR',20,28);ctx.fillText(`RUN ${Math.floor(score)}m`,680,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;p.vy+=1750*dt;const prev=p.y+p.h;p.y+=p.vy*dt;p.onGround=false;for(let i=0;i<plats.length;i++){const o=plats[i];if(!o.ground){o.x-=speed*dt;if(o.x+o.w<0)o.x=820+Math.random()*130}if(prev<=o.y&&p.y+p.h>=o.y&&p.x+p.w>o.x&&p.x<o.x+o.w&&p.vy>=0){p.y=o.y-p.h;p.vy=0;p.onGround=true}}p.rot=(p.rot||0)+dt*8;if(p.y>500){end(`Run ended at ${Math.floor(score)} meters.`);return}next-=dt;if(next<=0){const o=plats[1+Math.floor(Math.random()*2)];obs.push({x:o.x+o.w*.55,y:o.y,w:22,h:28+Math.random()*25});next=1+Math.random()*.7}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);for(const o of obs)if(p.x+p.w-4>o.x&&p.x+4<o.x+o.w&&p.y+p.h>o.y-o.h+4&&p.y<o.y){window.RecessPoints?.award?.(Math.floor(score/8),'Cube Rush');end(`Run ended at ${Math.floor(score)} meters.`);return}speed+=dt*4;setScore(score+dt*10);draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gdBeginnerLegacy(){const cfg=gdConfigs[gdLevel]||gdConfigs.stereo;let p={x:130,y:368,vy:0,w:32,h:32,onGround:true,rot:0},plats=[{x:0,y:402,w:900,h:5,ground:true},{x:390,y:335,w:220,h:12},{x:740,y:285,w:190,h:12}],obs=[{x:520,y:402,w:18,h:24}],speed=cfg.speed,next=cfg.next,last=performance.now(),old=false;const finish=cfg.finish,jump=()=>{if(p.onGround){p.vy=-640;p.onGround=false}};function draw(){ctx.fillStyle='#21165b';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.15)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}ctx.fillStyle='#14e6d4';plats.forEach(o=>ctx.fillRect(o.x,o.y,o.w, o.ground&&cfg.platforms&&score>18?0:o.h));ctx.save();ctx.translate(p.x+16,p.y+16);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-16,-16,32,32);ctx.restore();ctx.fillStyle='#ff4f9a';obs.forEach(o=>{ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w/2,o.y-o.h);ctx.lineTo(o.x+o.w,o.y);ctx.closePath();ctx.fill()});ctx.fillStyle='#ffe66d';ctx.fillRect(760,120,6,282);ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText(`${cfg.label} · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(score/finish*100))}%`,735,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;p.vy+=1550*dt;const prev=p.y+p.h;p.y+=p.vy*dt;p.onGround=false;plats.forEach(o=>{if(!o.ground){o.x-=speed*dt;if(o.x+o.w<0)o.x=830+Math.random()*100}if(prev<=o.y&&p.y+p.h>=o.y&&p.x+p.w>o.x&&p.x<o.x+o.w&&p.vy>=0){p.y=o.y-p.h;p.vy=0;p.onGround=true}});p.rot+=dt*6;if(p.y>500){if(practiceMode){p.y=368;p.vy=0;score=Math.floor(score/30)*30;setScore(score);showPracticeCheckpoint();}else{end(`${cfg.label} ended at ${Math.floor(score/finish*100)}%.`);return}}if(cfg.platforms&&score>18)plats[0].y=540;next-=dt;if(next<=0){const o=plats[1+Math.floor(Math.random()*2)];obs.push({x:o.x+o.w*.7,y:o.y,w:18,h:24});next=1.3+Math.random()*.8}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);for(const o of obs)if(p.x+p.w-4>o.x&&p.x+4<o.x+o.w&&p.y+p.h>o.y-o.h+4&&p.y<o.y){if(practiceMode){p.y=368;p.vy=0;score=Math.floor(score/30)*30;setScore(score);showPracticeCheckpoint();}else{end(`${cfg.label} ended at ${Math.floor(score/finish*100)}%.`);return}}speed+=dt*2;setScore(score+dt*10);if(score>=finish){end(`${cfg.label} complete! 100%`);return}draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
// Stereo Madness uses a fixed, readable obstacle chart like the reference level.
// Keep the other premade levels on the original platform generator.
function gdBeginner(){
  if(gdLevel!=='stereo')return gdBeginnerOriginal();
  const finish=gdConfigs.stereo.finish*25;
  let p={x:130,y:368,vy:0,w:32,h:32,onGround:true,rot:0},distance=0,last=performance.now(),old=false;
  const chart=[];for(let i=0;i<44;i++){const x=620+i*255;const h=i%9===5?42:i%5===2?34:28;chart.push({x,y:402,w:h>38?30:24,h});if(i%7===3)chart.push({x:x+34,y:402,w:24,h:28})}
  const coins=[760,1510,2290,3820,5360,6890,8440,9980].map(x=>({x,y:300,collected:false}));
  const pads=[{x:1280,w:46},{x:2360,w:46},{x:4620,w:46},{x:7440,w:46},{x:9720,w:46}];
  const jump=()=>{if(p.onGround){p.vy=-640;p.onGround=false}};
  function draw(){
    const g=ctx.createLinearGradient(0,0,800,500);g.addColorStop(0,'#21165b');g.addColorStop(1,'#101e4b');ctx.fillStyle=g;ctx.fillRect(0,0,800,500);
    ctx.strokeStyle='rgba(117,255,240,.15)';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}
    ctx.fillStyle='#14e6d4';ctx.fillRect(0,402,800,5);
    ctx.fillStyle='#ff4f9a';chart.forEach(o=>{const x=o.x-distance+p.x;if(x>-60&&x<840){ctx.beginPath();ctx.moveTo(x,o.y);ctx.lineTo(x+o.w/2,o.y-o.h);ctx.lineTo(x+o.w,o.y);ctx.closePath();ctx.fill()}});
    ctx.fillStyle='#ffe66d';pads.forEach(o=>{const x=o.x-distance+p.x;if(x>-60&&x<840){ctx.fillRect(x,392,o.w,10);ctx.fillRect(x+7,386,6,6);ctx.fillRect(x+o.w-13,386,6,6)}});
    coins.forEach(c=>{if(c.collected)return;const x=c.x-distance+p.x;if(x>-30&&x<830){ctx.strokeStyle='#ffe66d';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,c.y,11,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(255,230,109,.22)';ctx.fill()}});
    ctx.save();ctx.translate(p.x+16,p.y+16);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-16,-16,32,32);ctx.fillStyle='#21165b';ctx.fillRect(-8,-8,6,6);ctx.fillRect(5,-8,6,6);ctx.restore();
    ctx.fillStyle='#ffe66d';ctx.fillRect(760,120,6,282);ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(20,42,760,5);ctx.fillStyle='#ffe66d';ctx.fillRect(20,42,760*Math.min(1,distance/finish),5);ctx.fillStyle='white';ctx.font='bold 13px Audiowide,Arial';ctx.fillText(`STEREO MADNESS · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(distance/finish*100))}%`,735,28);ctx.font='bold 11px Arial';ctx.fillText(`COINS ${coins.filter(c=>c.collected).length}/${coins.length}`,20,68)
  }
  function loop(now){
    if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;
    distance+=255*dt;p.vy+=1550*dt;p.y+=p.vy*dt;p.onGround=false;if(p.y>=368){p.y=368;p.vy=0;p.onGround=true}p.rot+=dt*6;
    pads.forEach(o=>{const x=o.x-distance+p.x;if(p.x+p.w>x&&p.x<x+o.w&&p.y+p.h>=402&&p.y+p.h<430&&p.vy>=0){p.y=334;p.vy=-860;p.onGround=false}});
    coins.forEach(c=>{const x=c.x-distance+p.x;if(!c.collected&&Math.abs((p.x+p.w/2)-x)<22&&Math.abs((p.y+p.h/2)-c.y)<28){c.collected=true;window.RecessPoints?.award?.(25,'Geometry coin')}});
    for(const o of chart){const x=o.x-distance+p.x;if(p.x+p.w-4>x&&p.x+4<x+o.w&&p.y+p.h>o.y-o.h+4&&p.y<o.y){if(practiceMode){distance=Math.floor(distance/300)*300;p.y=368;p.vy=0;showPracticeCheckpoint();}else{end(`STEREO MADNESS ended at ${Math.floor(distance/finish*100)}%.`);return}}}
    if(p.y>500){if(practiceMode){distance=Math.floor(distance/300)*300;p.y=368;p.vy=0;showPracticeCheckpoint()}else{end(`STEREO MADNESS ended at ${Math.floor(distance/finish*100)}%.`);return}}
    setScore(Math.floor(distance/25));if(distance>=finish){end('STEREO MADNESS complete! 100%');return}draw();raf=requestAnimationFrame(loop)
  }raf=requestAnimationFrame(loop)
}
function gdBeginnerOriginal(){
  const cfg=gdConfigs[gdLevel]||gdConfigs.backtrack;
  let p={x:130,y:368,vy:0,w:32,h:32,onGround:true,rot:0},plats=[{x:0,y:402,w:900,h:5,ground:true},{x:390,y:335,w:220,h:12},{x:740,y:285,w:190,h:12}],spikes=[],speed=cfg.speed,next=0,last=performance.now(),old=false;
  const finish=cfg.finish,jump=()=>{if(p.onGround){p.vy=-640;p.onGround=false}};
  function resetCheckpoint(){p.y=368;p.vy=0;spikes=[];score=Math.floor(score/30)*30;setScore(score);showPracticeCheckpoint()}
  function draw(){
    ctx.fillStyle='#21165b';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.15)';
    for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}
    ctx.fillStyle='#14e6d4';plats.forEach(o=>{if(!o.ground||score<=18)ctx.fillRect(o.x,o.y,o.w,o.h)});
    ctx.fillStyle='#ff4f9a';spikes.forEach(o=>{if(o.x>-60&&o.x<840){ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w/2,o.y-o.h);ctx.lineTo(o.x+o.w,o.y);ctx.closePath();ctx.fill()}});
    ctx.save();ctx.translate(p.x+16,p.y+16);ctx.rotate(p.rot);ctx.fillStyle='#ffdc4a';ctx.fillRect(-16,-16,32,32);ctx.restore();
    ctx.fillStyle='#ffe66d';ctx.fillRect(760,120,6,282);ctx.fillStyle='white';ctx.font='bold 13px Audiowide,Arial';ctx.fillText(`${cfg.label} · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(score/finish*100))}%`,735,28)
  }
  function loop(now){
    if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!old)jump();old=j;
    p.vy+=1550*dt;const prev=p.y+p.h;p.y+=p.vy*dt;p.onGround=false;
    plats.forEach(o=>{if(!o.ground){o.x-=speed*dt;if(o.x+o.w<0)o.x=850+Math.random()*100}if((!o.ground||score<=18)&&prev<=o.y&&p.y+p.h>=o.y&&p.x+p.w>o.x&&p.x<o.x+o.w&&p.vy>=0){p.y=o.y-p.h;p.vy=0;p.onGround=true}});
    p.rot+=dt*6;if(p.y>500){if(practiceMode)resetCheckpoint();else{end(`${cfg.label} ended at ${Math.floor(score/finish*100)}%.`);return}}
    next-=dt;if(next<=0){const platform=score>18?plats[1+Math.floor(Math.random()*2)]:plats[0];spikes.push({x:platform.x+platform.w*.62,y:platform.y,w:22,h:28+Math.random()*16});next=cfg.next}
    spikes.forEach(o=>o.x-=speed*dt);spikes=spikes.filter(o=>o.x>-80);
    for(const o of spikes)if(p.x+p.w-4>o.x&&p.x+4<o.x+o.w&&p.y+p.h>o.y-o.h+3&&p.y<o.y){if(practiceMode)resetCheckpoint();else{end(`${cfg.label} ended at ${Math.floor(score/finish*100)}%.`);return}}
    setScore(score+dt*10);if(score>=finish){end(`${cfg.label} complete! 100%`);return}draw();raf=requestAnimationFrame(loop)
  }raf=requestAnimationFrame(loop)
}
function showPracticeCheckpoint(){const node=document.querySelector('#overlay-copy');if(node)node.textContent='Practice checkpoint reached — keep going!';}

// Pellet Dash mode: a fuller maze run adapted from the supplied reference.
// It keeps the site's existing score/progress hooks while adding lives,
// cherries, difficulty ramping, smarter ghosts, a timer, and a larger maze.
function pelletDash(){
  const tile=28;
  const map=[
    '############################',
    '#P...........##...........C#',
    '#.####.#####.##.#####.####.#',
    '#..........................#',
    '#.##.##.###.####.###.##.##.#',
    '#....##.....G..G.....##....#',
    '####.##.###.####.###.##.####',
    '#..........................#',
    '#.####.##.########.##.####.#',
    '#C.....##....##....##.....C#',
    '######.#####.##.#####.######',
    '#..........................#',
    '#.###.####.##..##.####.###.#',
    '#...G.......##.......G.....#',
    '#.###.####.##..##.####.###.#',
    '#..........................#',
    '#####.##.###.####.###.##.###',
    '#C....##.....G..G....##...C#',
    '#.##.##.###.####.###.##.##.#',
    '#..........................#',
    '#.####.#####.##.#####.####.#',
    '#....##.....####.....##....#',
    '#..........C....C..........#',
    '############################'
  ];
  const cols=map[0].length,rows=map.length;
  canvas.width=cols*tile;canvas.height=rows*tile;canvas.style.aspectRatio=`${cols}/${rows}`;
  const livesBox=document.querySelector('#pacman-lives-box'),pelletsBox=document.querySelector('#pacman-pellets-box'),timeBox=document.querySelector('#pacman-time-box');
  const livesEl=document.querySelector('#pacman-lives'),pelletsEl=document.querySelector('#pacman-pellets'),timeEl=document.querySelector('#pacman-time');
  [livesBox,pelletsBox,timeBox].forEach(node=>{if(node)node.hidden=false;});
  const level=Math.max(1,Math.min(100,pacmanDifficulty));
  const scoreMultiplier=pacmanScoreMultiplier(level);
  const pressure=(level-1)/99;
  const selected={playerDelay:Math.round(112+pressure*24),ghostDelay:Math.round(620-pressure*520),chaseChance:.02+pressure*.9,cherryMs:30000};
  const beginnerGrace=20000,rampDuration=60000;
  let grid=[],player={x:1,y:1,dir:{x:0,y:0},wanted:{x:0,y:0}},ghosts=[];
  let runScore=0,lives=3,pelletsLeft=0,cherryUntil=0,lastPlayerMove=0,lastGhostMove=0,lastCherrySpawn=0,runStartedAt=performance.now(),lastFrame=runStartedAt,lastHud=0,frames=0,fpsClock=runStartedAt,gameState='playing',hitCooldown=0,floating=[];
  const ghostColors=['#47c8ff','#ff4f8b','#9b6dff','#ff8a4c','#3ff0b5'];
  const dirs=[{x:0,y:-1},{x:0,y:1},{x:-1,y:0},{x:1,y:0}];
  const keyDir=()=>keys.ArrowLeft||keys.KeyA?{x:-1,y:0}:keys.ArrowRight||keys.KeyD?{x:1,y:0}:keys.ArrowUp||keys.KeyW?{x:0,y:-1}:keys.ArrowDown||keys.KeyS?{x:0,y:1}:null;
  map.forEach((row,y)=>row.split('').forEach((cell,x)=>{if(cell==='P'){player.x=x;player.y=y;} }));
  grid=map.map(row=>row.split('').map(cell=>cell==='#'?'#':cell==='P'||cell==='G'?' ':cell==='C'?'C':'.'));
  map.forEach((row,y)=>row.split('').forEach((cell,x)=>{if(cell==='G')ghosts.push({x,y,vx:x,vy:y,spawnX:x,spawnY:y,respawnUntil:0,color:ghostColors[ghosts.length%ghostColors.length]});}));
  grid[player.y][player.x]=' ';
  pelletsLeft=grid.flat().filter(cell=>cell==='.').length;
  function elapsed(now){return Math.max(0,now-runStartedAt);}
  function formatTime(ms){const seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
  function ramp(now){return Math.max(0,Math.min(1,(elapsed(now)-beginnerGrace)/rampDuration));}
  function activeGhostDelay(now){const progress=ramp(now);return Math.round(selected.ghostDelay+(760-selected.ghostDelay)*(1-progress));}
  function wrapX(x){return (x+cols)%cols;}
  function canMove(x,y){return y>=0&&y<rows&&grid[y][wrapX(x)]!=='#';}
  function cellAt(x,y){return y>=0&&y<rows?{x:wrapX(x),y}:null;}
  function addFloat(text,x,y,color){floating.push({text,x:x*tile+tile/2,y:y*tile+tile/2,color,born:performance.now()});}
  function updateHud(now){
    setScore(Math.floor(runScore));
    if(livesEl)livesEl.textContent=String(Math.max(0,lives));
    if(pelletsEl)pelletsEl.textContent=String(pelletsLeft);
    if(timeEl)timeEl.textContent=formatTime(elapsed(now));
    if(now-lastHud>450){const fpsEl=document.querySelector('#fps');if(fpsEl)fpsEl.textContent=String(Math.min(120,Math.round(frames*1000/Math.max(1,now-fpsClock))));frames=0;fpsClock=now;lastHud=now;}
  }
  function finishRun(title,text){gameState=title==='YOU WIN'?'won':'lost';running=false;cancelAnimationFrame(raf);document.querySelector('#overlay-title').textContent=title;document.querySelector('#overlay-copy').textContent=text;startBtn.textContent='PLAY AGAIN';overlay.hidden=false;updateHud(performance.now());}
  function movePlayer(now){
    if(now-lastPlayerMove<selected.playerDelay)return;
    lastPlayerMove=now;const requested=keyDir();if(requested)player.wanted=requested;
    const next=cellAt(player.x+player.wanted.x,player.y+player.wanted.y);if(next&&canMove(next.x,next.y))player.dir=player.wanted;
    const step=cellAt(player.x+player.dir.x,player.y+player.dir.y);if(!step||!canMove(step.x,step.y))return;
    player.x=step.x;player.y=step.y;const cell=grid[player.y][player.x];
    if(cell==='.'){grid[player.y][player.x]=' ';pelletsLeft-=1;const points=10*scoreMultiplier;runScore+=points;addFloat(`+${points}`,player.x,player.y,'#55e6a5');if(Math.floor(runScore/10)%5===0)window.RecessPoints?.award?.(5,'Maze dots');}
    if(cell==='C'){grid[player.y][player.x]=' ';cherryUntil=Math.max(cherryUntil,now)+selected.cherryMs;addFloat('+30s',player.x,player.y,'#ff5b7c');}
    if(pelletsLeft<=0){window.RecessPoints?.award?.(75,'Maze cleared');finishRun('YOU WIN',`Maze cleared at difficulty ${level}. Final score: ${Math.floor(runScore)}.`);}
  }
  function moveGhosts(now){
    if(now-lastGhostMove<activeGhostDelay(now))return;
    lastGhostMove=now;const powered=now<cherryUntil;
    ghosts.forEach(ghost=>{
      if(now<ghost.respawnUntil)return;
      const options=dirs.map(dir=>{const next=cellAt(ghost.x+dir.x,ghost.y+dir.y);return next&&canMove(next.x,next.y)?{dir,x:next.x,y:next.y}:null;}).filter(Boolean);if(!options.length)return;
      options.sort((a,b)=>{const da=Math.abs(a.x-player.x)+Math.abs(a.y-player.y),db=Math.abs(b.x-player.x)+Math.abs(b.y-player.y);return powered?db-da:da-db;});
      const choice=Math.random()<(selected.chaseChance*(.18+ramp(now)*.82))?options[0]:options[Math.floor(Math.random()*options.length)];ghost.x=choice.x;ghost.y=choice.y;
    });
  }
  function checkCollisions(now){
    if(now<hitCooldown)return;
    for(let i=ghosts.length-1;i>=0;i-=1){const ghost=ghosts[i];if(now<ghost.respawnUntil||ghost.x!==player.x||ghost.y!==player.y)continue;
      if(now<cherryUntil){const points=30*scoreMultiplier;runScore+=points;addFloat(`+${points}`,player.x,player.y,'#55e6a5');ghost.x=ghost.spawnX;ghost.y=ghost.spawnY;ghost.vx=ghost.spawnX;ghost.vy=ghost.spawnY;ghost.respawnUntil=now+1400;continue;}
      lives-=1;hitCooldown=now+1300;player.x=1;player.y=1;player.dir={x:0,y:0};player.wanted={x:0,y:0};if(lives<=0){finishRun('GAME OVER',`Final score: ${Math.floor(runScore)}. Try a different route at difficulty ${level}.`);}return;
    }
  }
  function countCherries(){return grid.flat().filter(cell=>cell==='C').length;}
  function spawnCherry(){if(countCherries()>=8)return;const open=[];for(let y=0;y<rows;y+=1)for(let x=0;x<cols;x+=1)if(grid[y][x]===' '&&!(player.x===x&&player.y===y)&&!ghosts.some(g=>g.x===x&&g.y===y))open.push({x,y});if(open.length){const pick=open[Math.floor(Math.random()*open.length)];grid[pick.y][pick.x]='C';}}
  function draw(now){
    ctx.clearRect(0,0,canvas.width,canvas.height);for(let y=0;y<rows;y+=1)for(let x=0;x<cols;x+=1){const px=x*tile,py=y*tile;ctx.fillStyle=grid[y][x]==='#'?'#172a68':'#0d152b';ctx.fillRect(px,py,tile,tile);if(grid[y][x]==='#'){ctx.fillStyle='rgba(71,200,255,.3)';ctx.fillRect(px+3,py+3,tile-6,2);ctx.fillStyle='rgba(13,18,48,.48)';ctx.fillRect(px+3,py+tile-5,tile-6,2);}else if(grid[y][x]==='.'){ctx.fillStyle='#fff3a6';ctx.beginPath();ctx.arc(px+tile/2,py+tile/2,4,0,Math.PI*2);ctx.fill();}else if(grid[y][x]==='C'){ctx.fillStyle='rgba(255,79,139,.22)';ctx.beginPath();ctx.arc(px+tile/2,py+tile/2,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff4f8b';ctx.beginPath();ctx.arc(px+tile/2,py+tile/2,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3ff0b5';ctx.fillRect(px+16,py+6,3,9);}}
    ghosts.forEach(ghost=>{const x=ghost.vx*tile+tile/2,y=ghost.vy*tile+tile/2;ghost.vx+=(ghost.x-ghost.vx)*.22;ghost.vy+=(ghost.y-ghost.vy)*.22;ctx.globalAlpha=now<ghost.respawnUntil?.35:1;const powered=now<cherryUntil;ctx.fillStyle=powered?'#55e6a5':ghost.color;ctx.beginPath();ctx.arc(x,y-2,12,Math.PI,0);ctx.lineTo(x+12,y+13);ctx.lineTo(x+6,y+9);ctx.lineTo(x,y+13);ctx.lineTo(x-6,y+9);ctx.lineTo(x-12,y+13);ctx.closePath();ctx.fill();ctx.fillStyle='#0a0d13';ctx.beginPath();ctx.arc(x-5,y-3,2.8,0,Math.PI*2);ctx.arc(x+5,y-3,2.8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;});
    const px=player.x*tile+tile/2,py=player.y*tile+tile/2,angle=Math.atan2(player.dir.y,player.dir.x)||0;ctx.save();ctx.translate(px,py);ctx.rotate(angle);ctx.fillStyle='#ffe45c';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,12,.22,Math.PI*2-.22);ctx.closePath();ctx.fill();ctx.restore();
    floating=floating.filter(item=>now-item.born<900);floating.forEach(item=>{const progress=(now-item.born)/900;ctx.globalAlpha=1-progress;ctx.fillStyle=item.color;ctx.font='900 16px Arial';ctx.textAlign='center';ctx.fillText(item.text,item.x,item.y-progress*22);});ctx.globalAlpha=1;ctx.textAlign='left';
    if(now<cherryUntil){ctx.fillStyle='rgba(255,91,124,.9)';ctx.fillRect(12,canvas.height-24,Math.min(190,((cherryUntil-now)/selected.cherryMs)*190),9);ctx.fillStyle='#fff';ctx.font='700 13px Arial';ctx.fillText(`CHERRY POWER ${Math.ceil((cherryUntil-now)/1000)}s`,12,canvas.height-30);}
    if(gameState==='playing'){const progress=ramp(now);ctx.fillStyle='rgba(10,13,19,.72)';ctx.fillRect(canvas.width-190,10,178,24);ctx.fillStyle='#fff';ctx.font='800 12px Arial';ctx.textAlign='right';ctx.fillText(elapsed(now)<beginnerGrace?`WARM-UP ${Math.ceil((beginnerGrace-elapsed(now))/1000)}s`:`DANGER RAMP ${Math.round(progress*100)}%`,canvas.width-20,27);ctx.textAlign='left';}
  }
  function loop(now){if(!running)return;const dt=Math.min(40,now-lastFrame);lastFrame=now;frames+=1;if(now-lastCherrySpawn>3800){lastCherrySpawn=now;spawnCherry();}movePlayer(now);moveGhosts(now);checkCollisions(now);updateHud(now);draw(now);if(running)raf=requestAnimationFrame(loop);}
  loop(runStartedAt);
}
function gdWaveLegacy(){let p={x:110,y:250,w:28,h:28},x=0,last=performance.now(),old=false,checkpoint=0;const total=4200;function draw(){ctx.fillStyle='#130d3d';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.18)';for(let gx=0;gx<800;gx+=40){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,500);ctx.stroke()}ctx.fillStyle='#ff4f9a';for(let i=0;i<14;i++){const ox=560+i*250-x;const gap=125+Math.sin(i*1.7)*55;ctx.beginPath();ctx.moveTo(ox,0);ctx.lineTo(ox+52,gap-22);ctx.lineTo(ox+104,0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(ox,500);ctx.lineTo(ox+52,gap+220);ctx.lineTo(ox+104,500);ctx.closePath();ctx.fill()}ctx.fillStyle='#ffdc4a';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='white';ctx.font='bold 13px Arial';ctx.fillText(`WAVE RUN · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(x/total*100))}%`,735,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const up=keys.Space||keys.ArrowUp||keys.KeyW;p.y+= (up?-335:335)*dt;x+=300*dt;const progress=Math.min(100,Math.floor(x/total*100));if(p.y<8||p.y+p.h>492){if(practiceMode){x=Math.floor(x/600)*600;p.y=250;showPracticeCheckpoint();}else{end(`WAVE RUN ended at ${progress}%.`);return}}if(x>=total){end('WAVE RUN complete! 100%');return}draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function gdWaveEasy(){let p={x:110,y:250,w:28,h:28},x=0,last=performance.now();const total=4200;function draw(){ctx.fillStyle='#130d3d';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.18)';for(let gx=0;gx<800;gx+=40){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,500);ctx.stroke()}ctx.fillStyle='#ff4f9a';for(let i=0;i<18;i++){const ox=560+i*250-x,gap=125+Math.sin(i*1.7)*55;ctx.beginPath();ctx.moveTo(ox,0);ctx.lineTo(ox+52,gap-22);ctx.lineTo(ox+104,0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(ox,500);ctx.lineTo(ox+52,gap+220);ctx.lineTo(ox+104,500);ctx.closePath();ctx.fill()}ctx.fillStyle='#ffdc4a';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='white';ctx.font='bold 13px Audiowide,Arial';ctx.fillText(`WAVE RUN · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(x/total*100))}%`,735,28)}function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const up=keys.Space||keys.ArrowUp||keys.KeyW;p.y+=(up?-335:335)*dt;x+=300*dt;const progress=Math.min(100,Math.floor(x/total*100));let hit=false;for(let i=0;i<18;i++){const ox=560+i*250-x,gap=125+Math.sin(i*1.7)*55;if(p.x+p.w>ox&&p.x<ox+104&&(p.y<gap-16||p.y+p.h>gap+224)){hit=true;break}}if(hit||p.y<8||p.y+p.h>492){if(practiceMode){x=Math.floor(x/600)*600;p.y=250;showPracticeCheckpoint();}else{end(`WAVE RUN ended at ${progress}%.`);return}}if(x>=total){end('WAVE RUN complete! 100%');return}draw();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)}
function dinoHitboxMode(){
  let p={x:105,y:390,vy:0,w:34,h:42,onGround:true},obs=[],speed=300,next=0,last=performance.now(),oldJump=false,night=0;
  const hitboxesOn=()=>Boolean(document.querySelector('#dino-hitboxes')?.checked);
  function jump(){if(p.onGround){p.vy=-620;p.onGround=false}}
  function draw(){
    const dark=Math.floor(night)%2===1,duck=keys.ArrowDown||keys.KeyS;
    ctx.fillStyle=dark?'#202b4d':'#f7f7f7';ctx.fillRect(0,0,800,500);
    ctx.fillStyle=dark?'#f5e98a':'#d9d9d9';ctx.beginPath();ctx.arc(dark?680:110,75,24,0,Math.PI*2);ctx.fill();
    ctx.fillStyle=dark?'#9aa8d0':'#d9d9d9';ctx.fillRect(180,92,58,4);ctx.fillRect(195,85,28,7);
    ctx.fillStyle=dark?'#b8c6e8':'#535353';ctx.fillRect(0,432,800,3);
    const playerBox={x:p.x,y:p.y+(duck?12:0),w:p.w+(duck?13:0),h:duck?30:p.h};
    ctx.fillRect(playerBox.x,playerBox.y,playerBox.w,playerBox.h);
    ctx.fillStyle=dark?'#202b4d':'#f7f7f7';ctx.fillRect(p.x+24,p.y+8+(duck?12:0),7,7);
    ctx.fillStyle=dark?'#ff9a62':'#535353';obs.forEach(o=>{if(o.type==='bird'){ctx.fillRect(o.x,432-o.h,o.w,8);ctx.fillRect(o.x+8,432-o.h-8,8,8);ctx.fillRect(o.x+o.w-5,432-o.h-8,8,8)}else{ctx.fillRect(o.x,432-o.h,o.w,o.h);if(o.h>32)ctx.fillRect(o.x-8,410-o.h,o.w+15,7)}});
    if(hitboxesOn()){
      ctx.save();ctx.lineWidth=2;ctx.setLineDash([6,4]);
      ctx.strokeStyle='#ff245d';ctx.strokeRect(playerBox.x,playerBox.y,playerBox.w,playerBox.h);
      ctx.fillStyle='#ff245d';ctx.font='bold 11px Arial';ctx.fillText('PLAYER',playerBox.x,Math.max(12,playerBox.y-6));
      ctx.strokeStyle='#00b8ff';obs.forEach(o=>{const y=432-o.h;if(o.type==='bird'){ctx.strokeRect(o.x,y,o.w,8);ctx.strokeRect(o.x+8,y-8,8,8);ctx.strokeRect(o.x+o.w-5,y-8,8,8)}else{ctx.strokeRect(o.x,y,o.w,o.h);if(o.h>32)ctx.strokeRect(o.x-8,410-o.h,o.w+15,7)}if(o.x>-80&&o.x<820){ctx.fillStyle='#00b8ff';ctx.fillText('OBSTACLE',Math.max(2,o.x),Math.max(12,y-6));}});
      ctx.setLineDash([]);ctx.fillStyle=dark?'#fff':'#535353';ctx.font='bold 11px Arial';ctx.fillText('HITBOXES ON · H TO TOGGLE',20,48);ctx.restore();
    }
    ctx.fillStyle=dark?'#fff':'#535353';ctx.font='bold 13px Arial';ctx.fillText('SPACE / ↑ JUMP · ↓ DUCK',20,28);ctx.fillText(`SPEED ${Math.round(speed)}`,680,28);
  }
  function loop(now){
    if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const j=keys.Space||keys.ArrowUp||keys.KeyW;if(j&&!oldJump)jump();oldJump=j;
    p.vy+=1450*dt;p.y+=p.vy*dt;if(p.y>=390){p.y=390;p.vy=0;p.onGround=true}next-=dt;
    if(next<=0){const type=Math.random()<.18?'bird':'cactus';obs.push({x:820,w:type==='bird'?30:18+Math.random()*18,h:type==='bird'?75:24+Math.random()*38,type});next=Math.max(.62,1.25-speed/850)}
    obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-70);const duck=keys.ArrowDown||keys.KeyS;
    for(const o of obs){const hit=p.x+p.w-5>o.x&&p.x+5<o.x+o.w;if(hit&&(o.type==='bird'?!duck&&p.y+20>432-o.h:p.y+p.h>432-o.h+3)){window.RecessPoints?.award?.(Math.floor(score/10),'Dino survival');end(`You survived ${score} meters.`);return}}
    speed+=dt*6;night+=dt*.16;setScore(score+Math.max(1,Math.floor(dt*10)));draw();raf=requestAnimationFrame(loop)
  }
  raf=requestAnimationFrame(loop)
}

function gdWave(){
  let p={x:110,y:250,w:28,h:28},distance=0,last=performance.now();
  const total=4200,spacing=205,obstacles=22,speed=330;
  function gapFor(i){return{top:152+Math.sin(i*1.37)*76,size:148-(i%4)*10}}
  function reset(){distance=Math.floor(distance/600)*600;p.y=250;showPracticeCheckpoint()}
  function draw(){
    ctx.fillStyle='#100a35';ctx.fillRect(0,0,800,500);ctx.strokeStyle='rgba(117,255,240,.2)';
    for(let gx=0;gx<800;gx+=40){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,500);ctx.stroke()}
    for(let gy=0;gy<500;gy+=40){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(800,gy);ctx.stroke()}
    ctx.fillStyle='#ff4f9a';for(let i=0;i<obstacles;i++){const ox=560+i*spacing-distance,g=gapFor(i);ctx.beginPath();ctx.moveTo(ox,0);ctx.lineTo(ox+52,g.top-24);ctx.lineTo(ox+104,0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(ox,500);ctx.lineTo(ox+52,g.top+g.size+24);ctx.lineTo(ox+104,500);ctx.closePath();ctx.fill()}
    ctx.fillStyle='#ffdc4a';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='rgba(255,255,255,.2)';ctx.fillRect(20,42,760,5);ctx.fillStyle='#ffe66d';ctx.fillRect(20,42,760*Math.min(1,distance/total),5);ctx.fillStyle='white';ctx.font='bold 13px Audiowide,Arial';ctx.fillText(`WAVE RUN · ${practiceMode?'PRACTICE':'NORMAL'}`,20,28);ctx.fillText(`${Math.min(100,Math.floor(distance/total*100))}%`,735,28)
  }
  function loop(now){
    if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const up=keys.Space||keys.ArrowUp||keys.KeyW;
    p.y+=(up?-370:370)*dt;distance+=speed*dt;const progress=Math.min(100,Math.floor(distance/total*100));let hit=false;
    for(let i=0;i<obstacles;i++){const ox=560+i*spacing-distance,g=gapFor(i);if(p.x+p.w>ox&&p.x<ox+104&&(p.y<g.top-16||p.y+p.h>g.top+g.size+16)){hit=true;break}}
    if(hit||p.y<8||p.y+p.h>492){if(practiceMode)reset();else{end(`WAVE RUN ended at ${progress}%.`);return}}
    if(distance>=total){end('WAVE RUN complete! 100%');return}draw();raf=requestAnimationFrame(loop)
  }raf=requestAnimationFrame(loop)
}
startBtn.addEventListener('click',()=>{if(game==='blocks')return;overlay.hidden=true;setScore(0);running=true;cancelAnimationFrame(raf);if(game==='gd'&&gdLevel==='wave')gdWave();else ({pacman:pelletDash,blocks,football,dino:dinoHitboxMode,gd:gdBeginner}[game]||pelletDash)()});
